name: Script Validator

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Setup nodeJS
      uses: actions/setup-node@v1
      with: 
        node-version: ${{matrix.node-version}}
    - name: Install packages
      run: npm install
    - name: Test
      run: npm run test
